#!/bin/bash

echo "This is the 'setup' RUNNING" 
pwd
ls -al
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
chezmoi init sanderverhoeve/dotfiles
chezmoi apply
echo "Setup is DONE"
